### ISSUE TITLE
Any way to set the html dynamically?

### ISSUE THREAD

**Issue by jforaker** [lucasferreira/react-native-webview-android#1]
Rather than passing a url, is there a way to pass a string of html like this?:
https://github.com/lwansbrough/react-native-canvas/blob/master/Canvas.js#L26

Would love to use this to get a canvas prototype working.

Great plugin by the way!  :+1:

**Comment by jforaker** [comment]
Aha i think i found it:

```
    @ReactProp(name = "url")
    public void setUrl(RNWebView view, @Nullable String url) {
        String summary = "<html><body>You scored <b>192</b> points.</body></html>";
        view.loadData(summary, "text/html", "UTF-8");
    }
```

works!

**Comment by lucasferreira** [comment]
You are right @jforaker 

I implemented the new method/attribute inside de component, now the attribute **html** is officially supported, as the native WebView does.

Please update your *react-native-webview-android* package and test ;)
