### ISSUE TITLE
Videos inside webview

### ISSUE THREAD

**Issue by razat2013** [lucasferreira/react-native-webview-android#12]
I am trying to embed youtube and vimeo videos inside Webview but its not working.

**Comment by lucasferreira** [comment]
Hi @razat2013 

It's seems to be an Android problem, not module fault.

Can you try this: http://stackoverflow.com/questions/17259636/enabling-html5-video-playback-in-android-webview

I guest that you have to put in your AndroidManifest.xml file this attribute:
android:hardwareAccelerated="true"

Att.

**Comment by kitolog** [comment]
I'm using html5 player in webview and all works fine.

**Comment by lucasferreira** [comment]
Thanks @kitolog for the tips ;)
