### ISSUE TITLE
Disable back-swipe functionality

### ISSUE THREAD

**Issue by MuruganDurai** [lucasferreira/react-native-webview-android#14]
Hi, Thanks for the simple and nice webview component. I am using this component (along with navigator) for loading a web based map. If I swipe the map its navigating to previous screen. Please let me know how to disable this functioanlity with some code example. Thanks.

**Comment by lucasferreira** [comment]
Hi @MuruganDurai,

The back-swipe changes Navigator state or control the history flux of webview?

**Comment by MuruganDurai** [comment]
Navigator State. Thanks mate.


________________________________

**Comment by lucasferreira** [comment]
If was navigator state, it's a behavior of Native Module.

Look in the API if have this options available: https://facebook.github.io/react-native/docs/navigator.html#content

If not, I can't help... you have to ask directly to RN team: https://github.com/facebook/react-native/issues
