### ISSUE TITLE
input type=file  does not work

### ISSUE THREAD

**Issue by ueun** [lucasferreira/react-native-webview-android#17]
input type=file  does not work,how to fix? thanks very much。

**Comment by lucasferreira** [comment]
It isn't a problem of *react-native-webview-android module*, it's a behavior of native webview in Android.

Hero more links to get info:
http://stackoverflow.com/questions/4944102/android-webview-file-input-field-filechooser-doesnt-show-up
http://stackoverflow.com/questions/28136144/android-webview-input-type-file
http://stackoverflow.com/questions/5907369/file-upload-in-webview

It's a little bit hard to implement, but you have to implement some hidden methods in Java Android's API, as said here: http://stackoverflow.com/a/28289585/1683407
