### ISSUE TITLE
Implement a bridge between react-native and webview?

### ISSUE THREAD

**Issue by iinterest** [lucasferreira/react-native-webview-android#18]
Such as the title. THX

**Comment by lucasferreira** [comment]
Officially we don't have this feature. Neither the native WebView component of React Native has.

But I know that is not hard to implement this in Android, you have to use a JSInterface or something.

Other possibility is using the URL system, sending *hashs* and capture in onNavigationStateChange event.

If you are in index.html and them add a hash to *index.html#callMyFunction* as a cheat, you can capture this "url change" in **onNavigationStateChange** event.

**Comment by iinterest** [comment]
OK，Thank you:)
