### ISSUE TITLE
Question: Does the webview persist cookies or have an API to let the users set cookies?

### ISSUE THREAD

**Issue by owais** [lucasferreira/react-native-webview-android#2]

**Comment by lucasferreira** [comment]
Hi @owais 

The main object of this module is mimic the native WebView *(for iOS)* API. In the native API there is no mention to Cookies methods or events... so I didn't implement nothing in this way...

But I'm researching in Android docs, I think is not hard to implement that support: http://stackoverflow.com/questions/17230757/how-to-enable-cookies-in-android-webview

**Comment by lucasferreira** [comment]
@owais 

I made an update in module, now *react-native-webview-android* persists cookie by default.

But there is no way to set cookies externally by now... only if you set and read them inside your html/site that is loaded in WebView.

**Comment by owais** [comment]
@lucasferreira Awesome. I'll try to send PRs in case I need more advanced support. 

Thanks

**Comment by scgough** [comment]
Hi there @lucasferreira - just using your WebView and there seems to be an issue with the Cookie setup. I've had to comment out ln 28-29, 37-38 & 40-41 in RNWebViewManager as I was getting the error:

11-09 14:03:21.465 1324-1324/com.myproject I/dalvikvm: java.lang.IllegalStateException: Call CookieSyncManager::createInstance() or create a webview before using this class

I'm new to react so can't give more info as yet but it seems to be something to do with setting up the cookie manager before a view is available.

**Comment by lucasferreira** [comment]
Hi @scgough 

What version of Android SDK are you using to compile the app?

**Comment by scgough** [comment]
@lucasferreira 24.3.2

**Comment by lucasferreira** [comment]
@scgough 

I don't have a way to test this version of SDK, in my setup the highest SDK that I have to test is 23.

But I read your error, and focus on that part *"or create a webview before using this class"*
and that is what I do, I publish a new version now of *react-native-webview-android* module.

In this new version I created the android WebView instance **before** calling the cookie class.

Is that what I can help by now... can you test this new version?

**Comment by scgough** [comment]
Hi @lucasferreira - i haven't forgotten about this but haven't had time to test. Apologies. Will try to get back to you about this
