### ISSUE TITLE
React Native 0.17 webview has android support

### ISSUE THREAD

**Issue by jawadrehman** [lucasferreira/react-native-webview-android#25]
Probably mention that this is only useful till version 0.16 ?

**Comment by lucasferreira** [comment]
Hi @jawadrehman 

I major of cases yes, but our implementation has a few more options to set in use of Android Webviews, like geolocation, javascript, cookies and etc.

**Comment by avishayil** [comment]
Can I make make changes like custom user agent, play HTMl5 videos, etc with the native component, or I have to use this module?
Do you know if the iPhone has the same problems?

**Comment by lucasferreira** [comment]
@avishayil I don't know yet, I didn't have enough time to test the official implementation.

But I think that *userAgent* you can't change because isn't in docs: https://facebook.github.io/react-native/docs/webview.html#content
