### ISSUE TITLE
Full Height cannot be set

### ISSUE THREAD

**Issue by MuruganDurai** [lucasferreira/react-native-webview-android#26]
Hi, Thanks for the nice tool. I cannot set full height to the device to the webview in RN android app. Tried with different methods but could not get it worked. RN version is 0.13.1.

**Comment by lucasferreira** [comment]
Do you use the "flex: 1" style in your views?

**Comment by MuruganDurai** [comment]
Yes. I used your example code.

**Comment by lucasferreira** [comment]
Hi @MuruganDurai 

Here a sample to you download: https://dl.dropboxusercontent.com/u/42999/temp/AwesomeProjectVideo.zip

In this sample, the youtube page are fully height loaded inside the project.

*PS*: don't forget to run **npm install** before *react-native run-android* command

**Comment by MuruganDurai** [comment]
Hi @lucasferreira, Thanks for your support. I checked the above code but still it did n't worked for me with my url.  I have shared my url to your email (panchorf@gmail.com), could you please check & let me know.

**Comment by lucasferreira** [comment]
@MuruganDurai 

What is your Android version? I know that are some old android versions that can't deal OK with SVG or Canvas.

**Comment by MuruganDurai** [comment]
Android 5.1 and react native version is 0.13.1.


________________________________

**Comment by lucasferreira** [comment]
You can't use React Native version 0.17.0?

**Comment by MuruganDurai** [comment]
I don't know whether I could update since am using RN at windows machine. What you suggest?

**Comment by lucasferreira** [comment]
Sorry but I can't test your setup on Windows.

In my Mac, I'd used React Native version 0.14.2, it's old too, but works like a charm.

I've recorded a video showing to you:
https://dl.dropboxusercontent.com/u/42999/temp/demo_svg.mp4

**Comment by MuruganDurai** [comment]
Thanks a ton @lucasferreira. I will upgrade to 0.14.2 and test & let u know the results.
