### ISSUE TITLE
No connection. 

### ISSUE THREAD

**Issue by seanlau555** [lucasferreira/react-native-webview-android#28]
When I using the disable cookies mode to login instagram, it said I have no connection.

**Comment by lucasferreira** [comment]
@seanlau555 

I think that you need cookie enabled to login in instagram page...

**Comment by seanlau555** [comment]
Oh, I find the solution. 
My situation is that I want to use the WebView and get token from instagram when the new user register. Then the cookies is OK to remove for the next registration. 

So, I just put this 
RCTNetworking.clearCookies((cleared) => {
                console.log(cleared);
            });

in the onNavigationStateChange. And everything is alright. Thanks!!!
