### ISSUE TITLE
Can't load url

### ISSUE THREAD

**Issue by terrysahaidak** [lucasferreira/react-native-webview-android#29]
Just trying to login Gitter. After successfully GitHub login it should redirect to Gitter app, but it displays just a dark background and that's it.

Also tried with React Native Webview and got the same issue which can be tracked [here](https://github.com/facebook/react-native/issues/5211).

**Comment by lucasferreira** [comment]
Hi @terrysahaidak 

I can't test specific URLs and his compatibilities with android native SDK webview component.

I guess that is a bigger problem them our module and react native webview.

Can you check if this is a Gitter compatibility problem?

**Comment by terrysahaidak** [comment]
I think it isn't a Gitter compatibility problem because there is an app for Android called Developers Talks (written in java) which uses native WebView for login Gitter and everything works great.
