### ISSUE TITLE
Inject JS

### ISSUE THREAD

**Issue by scgough** [lucasferreira/react-native-webview-android#3]
Hi there,
Great WebView - I was just wondering, is it possible to inject some javascript into the page at the point of loading being complete?

**Comment by lucasferreira** [comment]
Hi @scgough 

I implemented the **injectedJavaScript** attribute/method in a fresh version now, can you please update your package and test?

I used this technique: http://lexandera.com/2009/01/injecting-javascript-into-a-webview/ in Android/Java code.

But I think that maybe restrict in some cases of use...

**Comment by scgough** [comment]
Thanks, I'll give it a try!

**Comment by scgough** [comment]
Works perfectly @lucasferreira Thanks!
