### ISSUE TITLE
Android 0.19.0

### ISSUE THREAD

**Issue by johntom** [lucasferreira/react-native-webview-android#31]
Hi,
Followed all instructions
1) c:\React\NativeStarter>react-native run-android
....
FAILURE: Build failed with an exception.
* Where:
Build file 'C:\React\NativeStarter\android\app\build.gradle' line: 78
* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':RNWebView' could not be found in project ':app'.
* Try:
Run with --stacktrace option to get the stack trace. Run with                                                    --info                                                    or                                                      --debug                                                   option to get more log output.
BUILD FAILED

2) I got BUILD SUCCESSFUL with a secod attempt 
3)react-native start 
but get the following on start
![image](https://cloud.githubusercontent.com/assets/1877376/12870068/ee157ca2-cd00-11e5-8195-27289177e317.png)

Using RN 0.19.0
win10
genymotion
Thanls.
John

**Comment by afeef** [comment]
Hi @johntom I think you upgraded react-native from a previous version. Did you run ```react-native upgrade``` before starting the packager? [See react-native upgrading guide here](https://facebook.github.io/react-native/docs/upgrading.html)

**Comment by johntom** [comment]
Yes I did that and verified with npm info react-native|more. Perhaps I'm missing something.
![image](https://cloud.githubusercontent.com/assets/1877376/12873372/275f1de6-cd89-11e5-9645-3fd009c93d7b.png)

**Comment by johntom** [comment]
Also, I did get it to work with https://github.com/ivanph/react-native-webintent which is very similar to your repo for instructions. Please feel fee to close but I will followup if you want too.
John

**Comment by lucasferreira** [comment]
Hi folks, the things change after react native 0.18. 

I didn't have enough time to update the documentation but It's keep easy to load up the package inside a project. 

Here we have more info https://facebook.github.io/react-native/docs/native-modules-android.html#content

**Comment by dalgopower** [comment]
yes..I tried your RN webview-android with RN 0.19 and couldn't get it working.
MainActivity.java does not match the one on your Readme.md file.

so..I will try to follow this guide (https://facebook.github.io/react-native/docs/native-modules-android.html#content) as you mentioned above. However, I need little help.

In my understanding, I am supposed to..
1) edit 'android/setting.gradle' as described in your document
2) edit 'android/app/build.gradle' as described in your document

3) create a class such as 'WebViewAndroidModule' (which extends ReactContextBaseJavaModule)

4) edit 'node_modules/react-native-webview-android/src/main/java/com/burnweb/rnwebview/main/RNWebViewPackage.java' file > 'createNativeModule' method to add that module from 1)

5) edit 
android/app/src/main/java/com/{my-app-name}/MainActivity.java' file > 'getPackages' to add RNWebViewPackage


ok...now I need to ONE thing.
where do I put WebViewAndroidModule.java file???
Is it supposed to be in...

a) node_modules/react-native-webview-android/src/main/java/com/burnweb/rnwebview/main/

b) android/app/src/main/java/com/{my-app-name}/

??

thanks in advance

**Comment by lucasferreira** [comment]
Sorry folks, since react native 0.18 the README instructions are now
obsolete. I didn't have enough time to update the instructions but in RN
website have this path of upgrading.

Keep watch for my update in a few days (I am out in vacation right now,
without any computer access :/)

Em quinta-feira, 11 de fevereiro de 2016, Ji Jimmy Youn <
notifications@github.com> escreveu:

> yes..I tried your RN webview-android with RN 0.19 and couldn't get it
> working.
> MainActivity.java does not match the one on your Readme.md file.
>
> so..I will try to follow this guide (
> https://facebook.github.io/react-native/docs/native-modules-android.html#content)
> as you mentioned above. However, I need little help.
>
> In my understanding, I am supposed to..
> 1) edit 'android/setting.gradle' as described in your document
> 2) edit 'android/app/build.gradle' as described in your document
>
> 3) create a class such as 'WebViewAndroidModule' (which extends
> ReactContextBaseJavaModule)
>
> 4) edit
> 'node_modules/react-native-webview-android/src/main/java/com/burnweb/rnwebview/main/RNWebViewPackage.java'
> file > 'createNativeModule' method to add that module from 1)
>
> 5) edit
> android/app/src/main/java/com/{my-app-name}/MainActivity.java' file >
> 'getPackages' to add RNWebViewPackage
>
> ok...now I need to ONE thing.
> where do I put WebViewAndroidModule.java file???
> Is it supposed to be in...
>
> a)
> node_modules/react-native-webview-android/src/main/java/com/burnweb/rnwebview/main/
>
> b) android/app/src/main/java/com/{my-app-name}/
>
> ??
>
> thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucasferreira/react-native-webview-android/issues/31#issuecomment-182872259>
> .
>


-- 
Sent from Gmail Mobile

**Comment by lucasferreira** [comment]
Hi @johntom

I've updated the *react-native-webview-android* project and npm package.

I couldn't test on Windows right now, but in my mac, with ReactNative 0.20 it runs 100%.

I recommend you to install by *npm install* command, and use the configure/load proccess that I've updated inside the [README](https://github.com/lucasferreira/react-native-webview-android/blob/master/README.md).

**Comment by lucasferreira** [comment]
Hi @dalgopower

You have to use *npm install react-native-webview-android* inside the root of your RN project.

Before that you have to just load insider in your configs files as I recommend in README.

I don't need to create any Java files, all the things you need are embed inside *react-native-webview-android* package.
