### ISSUE TITLE
'nativeondraw failed' issue on Android 4.4.2

### ISSUE THREAD

**Issue by dalgopower** [lucasferreira/react-native-webview-android#34]
I think I successfully placed react-native-webview-android with React Native 0.19 ( following the guide on https://facebook.github.io/react-native/docs/native-components-android.html#content )
but the webview component did not load a page properly, showing blank.

ADB log showed..
'nativeondraw failed clearing to background color'

I turned off the hardware acceleration on the application (of my project) and on the view (of RNWebViewAndroid project)
I also tried to set width, height, and background color of the web view component
but none of the solutions I found on the internet did not work.

After googling, it seems that many people using KitKat experience the same problem, however no clear solution for react-native native UI component

Can anyone help me out?

**Comment by lucasferreira** [comment]
Neither official RN webview component works?

Em sábado, 13 de fevereiro de 2016, Ji Jimmy Youn <notifications@github.com>
escreveu:

> I think I successfully placed react-native-webview-android with React
> Native 0.19 ( following the guide on
> https://facebook.github.io/react-native/docs/native-components-android.html#content
> )
> but the webview component did not load a page properly, showing blank.
>
> ADB log showed..
> 'nativeondraw failed clearing to background color'
>
> I turned off the hardware acceleration on the application (of my project)
> and on the view (of RNWebViewAndroid project)
> I also tried to set width, height, and background color of the web view
> component
> but none of the solutions I found on the internet did not work.
>
> After googling, it seems that many people using KitKat experience the same
> problem, however no clear solution for react-native native UI component
>
> Can anyone help me out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucasferreira/react-native-webview-android/issues/34>.
>


-- 
Sent from Gmail Mobile

**Comment by dalgopower** [comment]
yes the official RN webview component did not work either. (but I did not check ADB log. I will try the official RN webview again)

And also I thought that the official RN webview did not support the webview to work on Android yet according to the page "http://www.reactnative.com/simple-react-native-android-module-to-use-androids-webview-inside-your-app/" (since it was written on 11/10/2015, not too long ago)

**Comment by lucasferreira** [comment]
Yes the official component now working with android, since RN 0.15 I
guess... You could try on your android project but I don't know if will
work in Kitkat if it had some official bug.

Em sábado, 13 de fevereiro de 2016, Ji Jimmy Youn <notifications@github.com>
escreveu:

> yes the official RN webview component did not work either. (but I did not
> check ADB log. I will try the official RN webview again)
>
> And also I thought that the official RN webview did not support the
> webview to work on Android yet according to the page "
> http://www.reactnative.com/simple-react-native-android-module-to-use-androids-webview-inside-your-app/"
> (since it was written on 11/10/2015, not too long ago)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucasferreira/react-native-webview-android/issues/34#issuecomment-183645913>
> .
>


-- 
Sent from Gmail Mobile

**Comment by lucasferreira** [comment]
Hi @dalgopower 

I've made a litlte sample to your tests in Genymotion, please download here: https://dl.dropboxusercontent.com/u/42999/temp/AwesomeProject.zip

Unzip, enter the directory and them hit/run *npm instal*.

All the dependencies will be installed, and after that you can run *react-native run-android*.

I've tested this sample project em Genymotion (in my Mac) with Android version 4.4.4 and 5.0. It loaded with success the Google homepage.
