### ISSUE TITLE
Version 1.0.13 requiring  React Native  >=0.19

### ISSUE THREAD

**Issue by tuneZola** [lucasferreira/react-native-webview-android#35]
Requiring  React Native  >=0.19 is a major not minor release. I think that the way you are going your versioning needs updating.  1.0.13 is a breaking change, that requires a different versioning strategy.

**Comment by lucasferreira** [comment]
Hi @tuneZola 

We are trying to keep up with breaking changes in RN core, like [this](https://github.com/facebook/react-native/commit/c1b7a369af7ca457819d682b15f47fae7e2732fc).
