### ISSUE TITLE
Geolocation in webview doesn't work when I use Navigation API

### ISSUE THREAD

**Issue by eMatsiyana** [lucasferreira/react-native-webview-android#37]
Hello, have you by any chance tried using google maps inside the webview? Whenever I use a Navigator the webview doesn't show anything and when I use the webview on its own it works.
The maps site is written in react js.

The combination of the Navigation API and the Webview somehow disables maps with geolcation and nothing shows in the webview.

Console has no errors.

The iOS version of the app works fine. I am using RN0.22

Browsing through RN code, it looks like if the parent 'View' has backgroundcolor, the maps do not show.
I am not sure what the connection between geolcation inside a webview is affected by the Navigation API.

**Comment by lucasferreira** [comment]
Hi @eMatsiyana 

Do you ask for geo location permissions in your app?

What version of Android are you testing? Are you using a real device or emulator?

**Comment by eMatsiyana** [comment]
Permissions are set yes,
Using android 5.0
Tried on both emulator and device with location services activated.

On Thursday, 31 March 2016, Lucas Ferreira <notifications@github.com> wrote:

> Hi @eMatsiyana <https://github.com/eMatsiyana>
>
> Do you ask for geo location permissions in your app?
>
> What version of Android are you testing? Are you using a real device or
> emulator?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/lucasferreira/react-native-webview-android/issues/37#issuecomment-204078142>
>


-- 





*Kind regardsEmmanuel MatsiyanaSoftware/Web DeveloperBsc(Hons**)*

* Computer Science+27747154090*

**Comment by lucasferreira** [comment]
OK,

Can you send some URL with this location problem to load inside a sample webview?

**Comment by eMatsiyana** [comment]
I created this repo with very minimal and basic example code of the issue:
[reactmaps-withnavigator](https://github.com/eMatsiyana/reactmaps-withnavigator)

For some reason, When I use the [Navigator](https://facebook.github.io/react-native/docs/navigator.html#content) The map just fails to load.

But Other sites that do not have Maps work very well.

**Comment by lucasferreira** [comment]
Hi @eMatsiyana 

As soon as I can, I will test your project and if I found something to help you, I will let you know ;)

**Comment by lucasferreira** [comment]
Hi @eMatsiyana 

I guess that we are facing some sort of bug in RN when using Navigator + WebView.

I found more details here https://github.com/facebook/react-native/issues/5211

But to help you, I've solved your problem, I've made a pull request in your sample, thats actually works:
https://github.com/eMatsiyana/reactmaps-withnavigator/pull/1/files

I've downloaded all your html files and change somethings in there, css and html/mobile stuffs:
https://github.com/lucasferreira/reactmaps-withnavigator/tree/master/maps-html

Please, tell me if I could help you in that ;)

**Comment by eMatsiyana** [comment]
Thank you so much!

This fixed the problem.

Much appreciated
