### ISSUE TITLE
video html5 don't go to full screen

### ISSUE THREAD

**Issue by magicvn** [lucasferreira/react-native-webview-android#38]
Hi Lucasferreira, 

I did set android:hardwareAccelerated="true" in your AndroidManifest.xml file. However, The video still didn't go fullscreen.

Anything else have to set?

Thanks for great component

**Comment by lucasferreira** [comment]
Hi,

Fullscreen really didn't work :/

To go on fullscreen mode you will need to go deeper in android and made a
full player with all controls and etc.

Em quinta-feira, 7 de abril de 2016, magicvn <notifications@github.com>
escreveu:

> Hi Lucasferreira,
>
> I did set android:hardwareAccelerated="true" in your AndroidManifest.xml
> file. However, The video still didn't go fullscreen.
>
> Anything else have to set?
>
> Thanks for great component
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lucasferreira/react-native-webview-android/issues/38>
>


-- 
Sent from Gmail Mobile
