### ISSUE TITLE
Not rendering google map inside Webview

### ISSUE THREAD

**Issue by prabakarviji** [lucasferreira/react-native-webview-android#39]
It's not rendering Google Map inside the web view on RN 0.19

**Comment by lucasferreira** [comment]
Hi @prabakarviji 

I think that is a bug, if you try the native webview the same problem happens.

We talk about this in this other closed issue: https://github.com/lucasferreira/react-native-webview-android/issues/37

**Comment by prabakarviji** [comment]
Thanks @lucasferreira
