### ISSUE TITLE
Redbox around webview

### ISSUE THREAD

**Issue by NishanthShankar** [lucasferreira/react-native-webview-android#4]
Hi,
I am not able to use the webView for some reason. I am only getting a redbox around the web view. Not sure if im doing something wrong

This is the Warning i get
Warning: Native component for "RNWebViewAndroid" does not exist. But I am able to view the component in console logs

**Comment by lucasferreira** [comment]
Hi @NishanthShankar 

I made a litlte sample of using, you can download here:
https://dl.dropboxusercontent.com/u/42999/temp/AwesomeProject.zip

Don't forget to run **npm install** first *(to download the dependencies)* and them **react-native run-android** to run in your emulator.

*P.S.: I'm using React Native 0.13.x version*

**Comment by NishanthShankar** [comment]
I am using 0.14.2. Could that be causing an issue? I've run **npm install** and **react-native run-android** . I am able to print the WebViewAndroid component. But getting a redbox around the view

**Comment by lucasferreira** [comment]
@NishanthShankar 

I upgraded the version of *RN to 0.14.2* in AwersomeProject (my sample that I sent to you).
And them I tested in Android version 5.1 - API 22, everthing goes OK, look:
![img](https://cloud.githubusercontent.com/assets/234495/11279742/70c4fcba-8ed9-11e5-9b57-fd78f0dcb4e8.png)

Here I can't see this redbox around the view...

**Comment by NishanthShankar** [comment]
I restarted my mac and it works now. sorry for the inconvenience once again

**Comment by lucasferreira** [comment]
You're welcome @NishanthShankar ;)
