### ISSUE TITLE
i want play embed youtube, but black screen.

### ISSUE THREAD

**Issue by gn02394847** [lucasferreira/react-native-webview-android#40]
i want play embed youtube, but black screen.

ex url :
https://www.youtube.com/embed/zETNXBcVBz4

**Comment by lucasferreira** [comment]
Hi @gn02394847 

Did you enabled hardware acceleration as described here?
https://github.com/lucasferreira/react-native-webview-android#tips-for-video-html5-inside-webview

PS.: Video player embed a web page it's possible, but enter in video fullscreen it isn't.
