### ISSUE TITLE
how to set headers?

### ISSUE THREAD

**Issue by MrPluto** [lucasferreira/react-native-webview-android#44]
how to set headers ,just like React Native's webview source?

**Comment by lucasferreira** [comment]
Hi @MrPluto,

There aren't a way to set the webview headers by now, just the userAgent.

But we can think in some to work with that need.

**Comment by MrPluto** [comment]
hey there. now I want use android webview to upload file. but i'm not familiar with android. can you add upload file function if you are free?
thanks a lot

**Comment by lucasferreira** [comment]
Hi @MrPluto 

Can you open another issue to talk about this new subject?

By the way in a html site/page with a form + post you can handle all the uploads without mix/handle with React Native code.

But if you want to select a file inside a html page and them handle that file with React Native, I recommend you to use another solutions, like this: https://github.com/marcshilling/react-native-image-picker

**Comment by MrPluto** [comment]
Yes of course we can. but i need use the web for the forum in my APP, and in the forum users can upload image . it works fine in iOS. but seems there need do more work to make it works in android.

**Comment by lucasferreira** [comment]
Hi @MrPluto 

According to this thread https://github.com/facebook/react-native/issues/5219 there is no oficial solution that works in 100% o Android's versions.

But, if you want to try I could implement some code to work in some versions of Android.

What do you think?

**Comment by MrPluto** [comment]
that's really nice if you can implement in some versions.  since React native  just support android 4.1+,so we can have a try

**Comment by lucasferreira** [comment]
Hi @MrPluto 

Can you try the last version of this module in your app?

I implemented a experimental input file support, now the chooser dialog are working in most of Android devices/versions.

;)

**Comment by lucasferreira** [comment]
Hi again @MrPluto 

did you test the new features? Can I close this issue?

**Comment by MrPluto** [comment]
sorry for that, i'm busy with my job  so i have no enough time, i have do a simple work and the dialog are working well. really thanks for this update.:beers:
