### ISSUE TITLE
Back/Forward Buttons

### ISSUE THREAD

**Issue by scgough** [lucasferreira/react-native-webview-android#5]
Hi there,
I was wondering - how would I go about adding in Back, Forward and Reload button functionality? I've tried but failed :/

**Comment by lucasferreira** [comment]
Hi @scgough 

I implemented this actions in the last version of module, please update your *react-native-webview-android* package and test it again.

The use is similar of native RN Webview iOS component, you use the *ref* of your WebViewAndroid instance and call of goBack, goForward and reload.
