### ISSUE TITLE
Any plans to override the URL handler of the webview(shouldOverrideUrlLoading)

### ISSUE THREAD

**Issue by prithsharma** [lucasferreira/react-native-webview-android#52]
To support links like mailto: etc from the webview. Currently it takes to -
`ERR_UNKNOWN_URL_SCHEME` error

**Comment by lucasferreira** [comment]
Hi @prithsharma 

I think that is the same problem of Alert and other dialogs in Android WebView, RN didn't deal OK with them.

Did you test the native implementation of React Native? https://facebook.github.io/react-native/docs/webview.html

Did you know if the "mailto:" works using them?

**Comment by prithsharma** [comment]
Ah ok. The alerts work well in react-native-webview-android, have you custom implemented them?

I'll test mailto for react native's original WebView and update here.

**Comment by lucasferreira** [comment]
Hi @prithsharma 

I'm very sorry for this late answer, but yes I have implemented a custom Alert for this cases.

But I didn't test mailto: dialogs and others.

Did you test in native RN webview component? They support mailto: and tel: hrefs?

**Comment by joeunha** [comment]
Hi @lucasferreira 

I was tested in Native WebView component, they support "tel:" and other custom scheme. (not support "mailto:") 

However, your code not support any kind of custom URL scheme. Would you have plan to solve this problem?
