### ISSUE TITLE
WebViewAndroid crashes app

### ISSUE THREAD

**Issue by jernejrus** [lucasferreira/react-native-webview-android#55]
I just upgraded my app to react 15.3.0 and react-native 0.32.0 and the app crashes each time when it tries to open a view which includes WebViewAndroid.
Does any one else had the same experience and manage to solve it?

**Comment by lucasferreira** [comment]
Hi @jernejrus 

I've updated the module code, can you update your install and try again?

**Comment by jernejrus** [comment]
Hello,

The reason why I used WebViewAndroid was, that it supported zooming on Android, while native WebView did not. Since in the last version that is also working on Android, I stopped using WebViewAndroid.
