### ISSUE TITLE
v1.1.8 seems to be a breaking update from v1.1.6

### ISSUE THREAD

**Issue by prithsharma** [lucasferreira/react-native-webview-android#58]
After upgrading, `react-native run-android` gives the following error:-

```
/node_modules/react-native-webview-android/android/src/main/java/com/burnweb/rnwebview/NavigationStateChangeEvent.java:19: error: no suitable constructor found for Event(int)
        super(viewId);
        ^
    constructor Event.Event() is not applicable
      (actual and formal argument lists differ in length)
    constructor Event.Event(int,long) is not applicable
      (actual and formal argument lists differ in length)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/qplum-5/Desktop/qplum-android-qfolio/node_modules/react-native-webview-android/android/src/main/java/com/burnweb/rnwebview/RNWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:RNWebView:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':RNWebView:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

React Native: 0.30.0
React: 15.2.0

If it's intentional and supposed to be breaking, we can modify the version number to reflect that.

**Comment by lucasferreira** [comment]
Hi @prithsharma 

Can you update your RN install to the lastest one? 0.33 version?

**Comment by lucasferreira** [comment]
Hi @prithsharma 

I've made a few changes to "try" to make the module compatible with newer and older versions.

Can you install the latest version of webview module (1.1.9) and try again?

**Comment by prithsharma** [comment]
Thanks @lucasferreira - I'll try and let you know. 
Since the project I am using this in is for a production app in my day-job, it might take some time to upgrade from 1.1.6 to 1.1.10. Will post here if any issues.

**Comment by simocl** [comment]
Hi @lucasferreira, I am facing the same issue with 
react-native-cli: 1.2.0
react-native: 0.27.2

I can't upgrade to the latest react-native because some of my libraries are not compatible with the latest.

Any suggestions?

Regards,

**Comment by lucasferreira** [comment]
Hi @simocl you could try to install one of older versions of my package.

But RN 0.27.2 it's to old for my new implementations (like upload), sorry =/
