### ISSUE TITLE
webview not showing anything

### ISSUE THREAD

**Issue by jawadrehman** [lucasferreira/react-native-webview-android#6]
hi

i am trying to load a url using the webview but its not showing anything

i have copy pasted your webviewandroid example

this is the logs i get

11-24 18:23:50.225  2224  2224 W art     : Attempt to remove non-JNI local reference, dumping thread
11-24 18:23:50.228  2224  2224 W AwContents: onDetachedFromWindow called when already detached. Ignoring
11-24 18:23:50.394  2224  2403 D ReactNativeJS: { url: 'https://www.google.com/',
11-24 18:23:50.394  2224  2403 D ReactNativeJS:   canGoForward: false,
11-24 18:23:50.394  2224  2403 D ReactNativeJS:   canGoBack: false,
11-24 18:23:50.394  2224  2403 D ReactNativeJS:   loading: true }
11-24 18:23:50.504  2224  2403 D ReactNativeJS: { url: 'https://www.google.co.uk/?gfe_rd=cr&ei=PKtUVte-L_Kq8weggJbABA',
11-24 18:23:50.504  2224  2403 D ReactNativeJS:   canGoForward: false,
11-24 18:23:50.504  2224  2403 D ReactNativeJS:   canGoBack: false,
11-24 18:23:50.504  2224  2403 D ReactNativeJS:   loading: true }
11-24 18:23:51.038  2224  2224 W BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 2224
11-24 18:23:53.103  2224  2403 D ReactNativeJS: { url: 'https://www.google.co.uk/?gfe_rd=cr&ei=PKtUVte-L_Kq8weggJbABA',
11-24 18:23:53.103  2224  2403 D ReactNativeJS:   canGoForward: false,
11-24 18:23:53.103  2224  2403 D ReactNativeJS:   canGoBack: false,
11-24 18:23:53.103  2224  2403 D ReactNativeJS:   loading: false }
11-24 18:23:54.910  2224  2224 W BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 2224

i am on react native 0.14.2 . 

any help would be appreciated

**Comment by lucasferreira** [comment]
Hi @jawadrehman 

Here a sample to you: https://dl.dropboxusercontent.com/u/42999/temp/AwesomeProject.zip

Don't forget to run *npm install* before calling *react-native run-android*.

I've tested with RN 0.14.2 in Genymotion emulator *(Android 5.1 - API 23)*.

**Comment by jawadrehman** [comment]
On my app

 21:59:43.297  2743  2743 E DataReductionProxySettingListener: No DRP key due to exception:java.lang.ClassNotFoundException: com.android.webview.chromium.Drp
11-24 21:59:43.315  2743  2791 W AudioManagerAndroid: Requires BLUETOOTH permission
11-24 21:59:43.347  2743  2743 W art     : Attempt to remove non-JNI local reference, dumping thread
11-24 21:59:43.353  2743  2743 W AwContents: onDetachedFromWindow called when already detached. Ignoring
11-24 21:59:43.372   940   940 E SELinux : avc:  denied  { find } for service=batteryproperties scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:healthd_service:s0 tclass=service_manager
11-24 21:59:43.467  2743  2789 W chromium: [WARNING:data_reduction_proxy_config.cc(423)] SPDY proxy OFF at startup
11-24 21:59:43.714  2743  2804 D         : HostConnection::get() New Host Connection established 0xa11fa2e0, tid 2804
11-24 21:59:44.296  2743  2743 W BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 2743


On the same emulator the webview seems to work fine .

**Comment by jawadrehman** [comment]
one of the things i have noticed though is that in your project build.gradle had compile "com.facebook.react:react-native:0.13.+" whereas mine had .14+

**Comment by lucasferreira** [comment]
This my *AwesomeProject* sample works there?

The problem is only inside **your** app?

the *0.13+* indicates that gradle can use any version equal or newer to 0.13 in your build.

**Comment by jawadrehman** [comment]
@lucasferreira I would have suspected the emulator  but then why would it work with your project on the very same emulator. I am using the host gpu on it so dont think thats the fault. There is something else at play I suspect. I have a kindle fire but i doubt that this will work on that.

Is it fine if i attach my build.gradle and other configuration files ?

**Comment by lucasferreira** [comment]
It's that OK, if you can isolate the part of you app that uses webview, zip that and send me.

**Comment by jawadrehman** [comment]
@lucasferreira in my attempt to get you the app i managed to fix it up. I have two things in mind that might have helped. 
a) my package.json didnt have the module listed (maybe a misconfig in my project - since i had run npm install react-native-webview-android --save ) so i manually put it in, did npm install and it was working

b) something to do with gradle not rebuilding the app properly ?

**Comment by lucasferreira** [comment]
I'm glad to hear that @jawadrehman 

About gradle if you need a more accurate control you can use Android Studio with your RN project.
