### ISSUE TITLE
Adding compile project(':RNWebView') to my project gradle causes error 

### ISSUE THREAD

**Issue by lorrainefox** [lucasferreira/react-native-webview-android#62]
After following the npm instructions and adding the entry into settings.gradle, I add 'compile project(':RNWebView')', without quotes - when I build I get the error: "Error:Configuration with name 'default' not found."

**Comment by lucasferreira** [comment]
Hi @lorrainefox 

I guess that you are missing some point of configurations... but nrpm link or "react-native link" can help you.

I suggest that you remove any configs that you've done in your project to install "react-native-webview-android" and them using the auto-config (link) from react-native:

```react-native link react-native-webview-android```

This command should configure everything to you (in correct files and Java files).
