### ISSUE TITLE
localStorage support

### ISSUE THREAD

**Issue by sanqianpiao** [lucasferreira/react-native-webview-android#64]
@lucasferreira: 
Thanks for your contribution.
I'm using webview in my project, and I noticed that there is no 'domStorageEnabled' property which  control the localStorage feature.
By default, 'domStorageEnabled' on iOS is enabled, but on android is not.
Could you please add 'domStorageEnabled' to webview.
Thanks!

**Comment by lucasferreira** [comment]
Hi @sanqianpiao 

This project has _domStorageEnabled_ by default:
https://github.com/lucasferreira/react-native-webview-android/blob/master/android/src/main/java/com/burnweb/rnwebview/RNWebView.java#L93

Check your Android Permissions if thins didn't work in your app.
