### ISSUE TITLE
Can I use this function onShouldStartLoadWithRequest

### ISSUE THREAD

**Issue by guiyongdong** [lucasferreira/react-native-webview-android#66]
I can use onShouldStartLoadWithRequest in iOS  but i can not use onShouldStartLoadWithRequest in android

**Comment by lucasferreira** [comment]
Hi @guiyongdong 

My Webview version is not oficial and doesn't follow strictly the RN Webview API, so some methods (and properties) are not implement in my version.

But today RN Webview (native/core version) runs very well in Android, so for average uses of webview you don't need my version at all.
