### ISSUE TITLE
How can I get the message that passed By the PC

### ISSUE THREAD

**Issue by combing520** [lucasferreira/react-native-webview-android#68]
In  RN  , I can set the method "onMessage" ,where，I can get the message that Passed by the PC , But I just 
can't find the same method int  "react-native-webview-android".

  I would know how can I  receive the message that PC  passed By   in  the webWiew?

Thanks

**Comment by combing520** [comment]
PC(Website)

**Comment by lucasferreira** [comment]
Now you can use onMessage #91
