### ISSUE TITLE
webview not show 

### ISSUE THREAD

**Issue by wbpmrck** [lucasferreira/react-native-webview-android#70]
I follow the instruction and run the demo,but the webview **doesn't show on screen.**

**But** I can catch the **onNavigationStateChange** event and get log in console.

my version of RN is  `0.42`,and build tool version is `com.android.tools.build:gradle:2.2.0`

does anyone has the same problem?

**Comment by lucasferreira** [comment]
Hi @wbpmrck 

Have you styled your webview? Something with width and height or using flex: 1.

If you catch the onNavigationStateChange event, I guess that your webview are "invisble".

**Comment by longzhi** [comment]
@wbpmrck Have you solved this problem?
