### ISSUE TITLE
Source attribute not working on require file

### ISSUE THREAD

**Issue by metallurgical** [lucasferreira/react-native-webview-android#71]
In original react-native `WebView`, i can load html source using  :

```javascript
var mainHtml = require('./MainHtml.html');
.......
<WebView
    .......
     source={mainHtml} />
```

but if i use `WebViewAndroid` instead of `WebView` component, i got this error :

```javascript
Warning: Failed prop type: Invalid prop `source` of type `number` supplied to `WebViewAndroid`, expected `object`.
```
It quote about expecting object, i tried `source={{mainHtml}}`, but it does not make sense as i didnt know what key should be used

**Comment by lucasferreira** [comment]
Hello,

Try this:

source={{html: mainHtml}}

**Comment by metallurgical** [comment]
No luck, I did that, still not showing anything

**Comment by joeferraro** [comment]
@lucasferreira I'm seeing the same behavior

**Comment by anil-kumar-singh** [comment]
anyone find the solution.

**Comment by lucasferreira** [comment]
Hi guys,

If you could put your html in `android/app/src/main/assets/your_html_file.html` you could load in webview like that:

<WebView
    .......
     source={{ uri: "file:///android_asset/your_html_file.html" }} />

I think that could help ;)
