### ISSUE TITLE
Will WebView onMessage can be supported?

### ISSUE THREAD

**Issue by jaycie** [lucasferreira/react-native-webview-android#73]
When I  called window.postMessage, I found it's not be supported.

**Comment by lhang** [comment]
We need this feature too

**Comment by vincentmsx** [comment]
We need this feature too

**Comment by lucasferreira** [comment]
Hi @andriichernenko, could you help us with that new featured?

**Comment by andriichernenko** [comment]
@lucasferreira Sorry, I don't think I can.

**Comment by lucasferreira** [comment]
Supported now with this new PR #91
