### ISSUE TITLE
can this work with expo?

### ISSUE THREAD

**Issue by stefanflondor** [lucasferreira/react-native-webview-android#85]
I'm trying to use this with expo, but when i try to show the WebViewAndroid component, I get an error:
Warning: Native component for "RNWebViewAndroid" does not exist

Can this work with expo or what I have to do.

**Comment by lucasferreira** [comment]
Hi @stefanflondor 

I don't have much experience with expo, can Expo works with packages out-of-box? It's possible to install and all npm packages in thats kinds of project?
