### ISSUE TITLE
Send event from webview to react native

### ISSUE THREAD

**Issue by sonnylazuardi** [lucasferreira/react-native-webview-android#9]
Is there any way to send event from web view to react native? thanks

**Comment by lucasferreira** [comment]
Officially we don't have this feature. Neither the native WebView component of React Native has.

But I know that is not hard to implement this in Android, you have to use a JSInterface or something.

Other possibility is using the URL system, sending hashs and capture in onNavigationStateChange event.

If you are in index.html and them add a hash to index.html#callMyFunction as a cheat, you can capture this "url change" in onNavigationStateChange event.

**Comment by sonnylazuardi** [comment]
@lucasferreira thanks for the solution :+1:
