### ISSUE TITLE
blank component

### ISSUE THREAD

**Issue by spearmootz** [lucasferreira/react-native-webview-android#90]
i dont know why i get a blank screen when i use this module. im trying this out on index.js

```import React, { Component } from 'react';
var WebViewAndroid = require('react-native-webview-android');

import { AppRegistry } from 'react-native';

class Whatever extends Component {
  render () {
    return <WebViewAndroid url='https://www.google.com' javaScriptEnabled={true}
      geolocationEnabled={false} style={{ flex: 1 }} />;
  }
}

AppRegistry.registerComponent('whatever', () => Whatever);
```

**Comment by guyzmo** [comment]
I'm also getting a blank component trying this module. Not sure what I might have done wrong, I have no build time or compile time error.

**Comment by stefanflondor** [comment]
same for me

**Comment by croftman** [comment]
Same here !

`
import React, { Component } from 'react';
import {
    AppRegistry,
    Platform,
    StyleSheet,
    Text,
    View,
    WebView
} from 'react-native';

var WebViewAndroid = require('react-native-webview-android');
var SITE_URL = "https://google.fr";

type Props = {};
export default class App extends Component<Props> {

    render() {
        return <WebViewAndroid ref="webViewAndroidSample" javaScriptEnabled={true} geolocationEnabled={false} builtInZoomControls={false} url={SITE_URL} />;
    }
}`

**Comment by lucasferreira** [comment]
Hi @croftman 

Please try to insert your webview inside a View, and please try to put some style with and height or flex: 1 in your container and WebViewAndroid.

**Comment by croftman** [comment]
Nice ! It works just ith flex :1 :) Thank you !

**Comment by kkureli** [comment]
If don't have, add https beginning of the url
