### ISSUE TITLE
Error: ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by smitthakkar1** [lucasferreira/react-native-webview-android#97]
I am trying to render a webpage but it's giving me `Error: ERR_UNKNOWN_URL_SCHEME`.

I tried rendering other sites like Google, Facebook and it's working fine. below is my code.

```
    const URL  = "https://stellarterm.com";

        <WebViewAndroid 
          url={URL}
          style={{flex:1}}
        /> 
```

Above code renders "Webpage Not Available" with error code "ERR_UNKNOWN_URL_SCHEME".

**Comment by lucasferreira** [comment]
Hi @smitthakkar1 

Are you responsible for https://stellarterm.com website or just developing some app that need to use that URL?

**Comment by smitthakkar1** [comment]
Well, I am just developing some app that needs to use that.

**Comment by smitthakkar1** [comment]
By the way, if it's something that time consuming for you then you can skip it as I found another way.

I used ```<WebView>``` component by React-Native and injected a script into it which change the initial-scale in ```<meta>```
